### ISSUE TITLE
凭证角色化时丢失了参与方，如果想加上参与方该怎么处理？

### ISSUE THREAD

**Issue by aluckyu** [behring/8x-flow-diagram#4]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/8722559/156907776-ee6ce004-ce4e-455f-b764-d8f8c7669d72.png">
例如图上的专栏付款确认想加上参与方该怎么处理？

**Comment by behring** [comment]
默认已经会在凭证角色化后的凭证显示参与方，如果先要隐藏参与方，请调用类似如下方法evidence.play(paymentInReaderSubscriptionContext.confirmation, hideParty = true)。
